# Generated by Django 2.0.6 on 2019-09-25 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('page_number', models.IntegerField(default=0)),
                ('genre', models.CharField(max_length=200)),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
